### ISSUE TITLE
Ladar data set

### ISSUE THREAD

**Issue by YunkaiZHOU** [yizhou-wang/RODNet#46] opened 2022-03-17 08:31 UTC
Hello！I opened one of them There are many groups of data in the NPY file. Convert NPY files into pictures to get vertical lines.I would like to ask what is the meaning of the data in the radar data set.
![FR5TQCWU916$V8K%GF3Q}CN](https://user-images.githubusercontent.com/101783779/158768542-56a068f5-504e-43d1-9e27-61673db12a0c.png)
![)NKXZDJJUOA`S(}NSA}~AMW](https://user-images.githubusercontent.com/101783779/158768879-b8b85775-0fdb-49b7-92b5-5d8d0ebb43b3.png)

**Comment by yizhou-wang** [comment] 2022-03-17 08:37
Each `npy` file is a radar data chirp with a dimension of 128x128x2 in range-azimuth coordinates. Please read the detailed description in our RODNet paper. 

Duplicate of #40

**Closed as completed** 2022-04-04 22:53 UTC
