### ISSUE TITLE
Question with images in test data set

### ISSUE THREAD

**Issue by kathy-lee** [yizhou-wang/RODNet#15] opened 2021-03-02 16:09 UTC
Hi yizhou,

thanks for your code sharing of RODNet! I have a small question about test data set: I reorganize the data files as you showed the data file structure in CRUW devkit, but I got an error during running 'perpare_data.py', because it cannot find image file in test subdir. But I thought in test stage there will only be radar data and no image file. Could you help me to make this clear? Thanks!

**Comment by chunguangqu** [comment] 2021-03-04 09:48
I encountered the same problem as you, have you found a solution?Thank you

**Comment by kathy-lee** [comment] 2021-03-04 10:06
Hi @chunguangqu ,
after trying I found 'prepare_data.py' can run through by: choose samples from training set and just let them be test samples. The RODNet does only use radar data as network input, the images are only for visualization use. So I think it's not an error, but need to change some snippets for doing test without image data.

**Comment by yizhou-wang** [comment] 2021-03-05 21:22
Duplicate of #6 

To prepare `test.pkl` file, you can just comment the image paths out. 
@kathy-lee Yes, you are right. the RODNet does not require images as input during testing.

**Closed** 2021-03-06 00:12 UTC
