### ISSUE TITLE
What is the specific model of the millimeter wave radar used and how to obtain RF images?

### ISSUE THREAD

**Issue by leo038** [yizhou-wang/RODNet#61] opened 2022-08-30 05:39 UTC
What is the specific model of the millimeter wave radar used?  Another question is how to obtain the RF images, since the original radar echo data is more complex and not two-dimensional(range and azimuth).

**Comment by yizhou-wang** [comment] 2022-10-09 01:22
Duplicate of #40

**Closed as completed by yizhou-wang** 2022-10-09 01:22 UTC
