### ISSUE TITLE
prepare_dataset for test

### ISSUE THREAD

**Issue by idokazma** [yizhou-wang/RODNet#22] opened 2021-05-12 15:56 UTC
I read the closed issues about prepare_dataset.py on the testset (fails because there are no image_paths), but even if you ignore that (you can't just comment it...), how can you run the test.py? It also looks for the image_paths and breaks.

Should I rewrite it all? or is there a small and smart fix?

thanks

**Comment by yizhou-wang** [comment] 2021-05-28 00:47
Duplicate of #6

**Closed** 2022-01-27 02:49 UTC
