### ISSUE TITLE
How to conduct the angle FFT？

### ISSUE THREAD

**Issue by leo038** [yizhou-wang/RODNet#62] opened 2022-09-01 09:01 UTC
The angle FFT is conducted along the different receivers antennas, for example, if there are 8 virtual antennas , dose it mean a 8 points FFT is conduct?

**Comment by leo038** [comment] 2022-09-01 11:20
Sure we can do a FFT more than 8 points, but the  length of angle in time domain is 8 points?

**Comment by leo038** [comment] 2022-09-13 09:54
@yizhou-wang

**Comment by yizhou-wang** [comment] 2022-10-09 01:21
Please find code for angle FFT here: https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification.

Duplicate of #40

**Closed as completed by yizhou-wang** 2022-10-09 01:21 UTC
