### ISSUE TITLE
could you tell me how to do radar data processing: adc data --> range fft --> angle fft --> save to .npy file? thank you very much!

### ISSUE THREAD

**Issue by Linda0111** [yizhou-wang/RODNet#57] opened 2022-07-22 12:36 UTC
Can you provide a code about this?

**Comment by leo038** [comment] 2022-09-13 09:56
I also want to konw this.

**Comment by yizhou-wang** [comment] 2022-10-09 01:18
Duplicate of #40

**Closed as completed by yizhou-wang** 2022-10-09 01:18 UTC
