### ISSUE TITLE
Cannot run test.py file

### ISSUE THREAD

**Issue by chencaichang** [yizhou-wang/RODNet#12] opened 2021-02-19 02:19 UTC
When I run the test.py file, it gives the following error.
Traceback (most recent call last):
  File "tools/test.py", line 165, in <module>
    image_paths = data_dict['image_paths'][0]
KeyError: 'image_paths'
As far as I know, during the testing phase, there should be no need for images. And I have deleted the image path when generating the test/.pkl file. 
Has anyone met this problem?
Thank you very much for your reply.

**Comment by yizhou-wang** [comment] 2021-02-19 08:46
Duplicate of #6 
Please refer to issue #6.

**Closed** 2021-02-20 02:40 UTC
